#pragma once

#define VIAL_KEYBOARD_UID {0x7A, 0xAD, 0x62, 0x38, 0x85, 0x84, 0x4C, 0xD1}
#define VIAL_UNLOCK_COMBO_ROWS {0, 3}
#define VIAL_UNLOCK_COMBO_COLS {0, 13}

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BREATHING

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100

#define RGB_MATRIX_DEFAULT_HUE 234
#define RGB_MATRIX_DEFAULT_SAT 128
#define RGB_MATRIX_DEFAULT_VAL 50

// reduce EEPROM usage
// #define VIAL_TAP_DANCE_ENTRIES 4
// #define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
